services:
  - type: web
    name: flask-app
    env: python
    region: oregon
    plan: free
    buildCommand: ""
    startCommand: "gunicorn -w 4 -b 0.0.0.0:5000 app:app"
    envVars:
      - key: FLASK_ENV
        value: production
    dockerfilePath: ./Dockerfile
